version: "3.8"

services:
  web:
    build: ./backend
    container_name: fastapi_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - mongo
    volumes:
      - shared-data:/shared

  worker:
    build: ./backend
    container_name: celery_worker
    command: celery -A app.tasks.workflow_tasks.celery_app worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - mongo
    volumes:
      - shared-data:/shared

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
